### ISSUE TITLE
Ubuntu Touch

### ISSUE THREAD

**Issue by sjehuda** [Customrombay/customrombay.org#1]
Ubuntu Touch works great on [Hammerhead](https://customrombay.org/google-hammerhead/) devices.

**Comment by PiotrZPL** [comment]
Support for syncing the database with Ubuntu Touch and PostmarketOS is planned. It would be useful if someone could provide parsable files to be used for this purpose.

**Comment by sjehuda** [comment]
On Thu, 29 Jun 2023 02:54:36 -0700
Piotr Lange ***@***.***> wrote:

> Support for syncing the database with Ubuntu Touch and PostmarketOS
> is planned. It would be useful if someone could provide parsable
> files to be used for this purpose.
> 

What do you mean by parsable files?

Do you mean to files as shown at https://customrombay.org/contributing/ ?

**Comment by PiotrZPL** [comment]
Look at [the database repo](https://github.com/Customrombay/database#readme). ROMs need to provide some kind of parsable files (APIs/devices.json) for my scripts to read which devices they support.

**Comment by sjehuda** [comment]
I'll ask at Divest OS.

Would HTML scrapping or reading from git repository be acceptable?

**Comment by PiotrZPL** [comment]
My scripts already read quite a lot from git repositories, so it's fine. However, if someone wants to scrape HTML, I will accept their pull request, but won't write scraping scripts myself.

**Comment by PiotrZPL** [comment]
I'm working on adding support for syncing with Ubuntu Touch right now. See: [d931f07a4379e50ca55f541c4db44674e4c69eaa](https://github.com/Customrombay/database/commit/d931f07a4379e50ca55f541c4db44674e4c69eaa)

**Comment by PiotrZPL** [comment]
Support for Ubuntu Touch fully added, closing.
