### ISSUE TITLE
NixOS & postmarketOS

### ISSUE THREAD

**Issue by sjehuda** [Customrombay/customrombay.org#2]
For [enchilada](https://customrombay.org/oneplus-enchilada/) and other devices.

**Comment by PiotrZPL** [comment]
For PostmarketOS, see #1

**Comment by PiotrZPL** [comment]
Support for syncing with Mobile NixOS was finally added in [cc3c385](https://github.com/Customrombay/database/commit/cc3c385d3aadee712cf77b8040b5eca91a6587a0). Thank you for your input. Closing...

**Comment by sjehuda** [comment]
Great! Thank you, Piotr ';-)
