### ISSUE TITLE
[Question] Only official ROMs are accepted to be in list?

### ISSUE THREAD

**Issue by HemanthJabalpuri** [Customrombay/customrombay.org#5]
@PiotrZPL 
Thanks for the website which lists ROMs cleanly.

I can't able to find any info regarding my question in your website 'About' page or Contributing page. Can you please clear this for me, so that I can contribute for my device in future (Moto G52 rhode)

Thanks

**Comment by PiotrZPL** [comment]
No, every custom ROM can be accepted to be in the list. This includes unofficial ROMs. However, they have to be marked as unofficial and appropriate links should be provided.

**Comment by PiotrZPL** [comment]
If one ROM has builds with multiple Android versions for one device, only the newest Android version should be included in the list. Similarly, if both official and unofficial builds of one custom ROM for one device exist, only the official one should be included.

**Comment by PiotrZPL** [comment]
Thanks. I will review the changes within a week.
