### ISSUE TITLE
oneplus-onyx

### ISSUE THREAD

**Issue by sjehuda** [Customrombay/customrombay.org#6]
An unofficial LineageOS version can be found at https://github.com/ChzeRub/Lineage-20.0-OTA via https://xdaforums.com/t/rom-unofficial-lineageos-20-for-onyx.4642371/

**Comment by PiotrZPL** [comment]
Added in [4db281d](https://github.com/Customrombay/database/commit/4db281dbd03d5d7a2165307df9c4ce65084a1b72).

**Comment by PiotrZPL** [comment]
Thank you for your input!

**Comment by sjehuda** [comment]
You are welcome!

When will it be visually realized? https://customrombay.org/oneplus-onyx/

**Comment by PiotrZPL** [comment]
@sjehuda The changes should now be visible.

**Comment by sjehuda** [comment]
Thank you.

The link that I think should be there is
https://github.com/ChzeRub/Lineage-20.0-OTA instead of
https://github.com/LineageOS-UL

**Comment by PiotrZPL** [comment]
I intentionally put the LineageOS-UL link for the ROM. I believe it is more helpful in describing what actually this ROM is.

If you click the link on the right, you are redirected to the XDA thread. So I think it's fine.

**Comment by sjehuda** [comment]
Pardon.

I did not notice the link at the right.

It seems good to me.

Thank you
